version: '3'

networks:
  communication: {}
services:
  server:
    restart: always
    build:
      context: server
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./server:/code
    command: python manage.py runserver 0.0.0.0:8080
    ports:
      - "8080:8080"
    networks:
      -  communication
  frontend:
    build:
      context: front/app
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./front/app:/app
    ports:
      - "4200:4200"
    networks:
      - communication
volumes:
  myapp: