version: '3'

networks:
  communication: {}
services:
  server:
    restart: always
    build:
      context: api
    command: python manage.py runserver 0.0.0.0:8080
    ports:
      - "8080:8080"
    networks:
      -  communication
  frontend:
    build:
      context: front/app
    ports:
      - "4200:4200"
    networks:
      - communication
  